using Registration.Domain.Lookups;

namespace Registration.Persistence.Seeding;

/// <summary>
/// Fixed seed data for the Governorate and City lookups, applied through EF Core
/// migrations (HasData). Identifiers are stable so they can be referenced safely.
/// </summary>
public static class LookupSeedData
{
    public static IReadOnlyList<Governorate> Governorates { get; } = new[]
    {
        new Governorate(1, "Cairo", "القاهرة"),
        new Governorate(2, "Giza", "الجيزة"),
        new Governorate(3, "Alexandria", "الأسكندرية"),
        new Governorate(4, "Dakahlia", "الدقهلية"),
        new Governorate(5, "Red Sea", "البحر الأحمر"),
        new Governorate(6, "Beheira", "البحيرة"),
        new Governorate(7, "Fayoum", "الفيوم"),
        new Governorate(8, "Gharbiya", "الغربية"),
        new Governorate(9, "Ismailia", "الإسماعلية"),
        new Governorate(10, "Menofia", "المنوفية"),
        new Governorate(11, "Minya", "المنيا"),
        new Governorate(12, "Qaliubiya", "القليوبية"),
        new Governorate(13, "New Valley", "الوادي الجديد"),
        new Governorate(14, "Suez", "السويس"),
        new Governorate(15, "Aswan", "اسوان"),
        new Governorate(16, "Assiut", "اسيوط"),
        new Governorate(17, "Beni Suef", "بني سويف"),
        new Governorate(18, "Port Said", "بورسعيد"),
        new Governorate(19, "Damietta", "دمياط"),
        new Governorate(20, "Sharkia", "الشرقية"),
        new Governorate(21, "South Sinai", "جنوب سيناء"),
        new Governorate(22, "Kafr Al sheikh", "كفر الشيخ"),
        new Governorate(23, "Matrouh", "مطروح"),
        new Governorate(24, "Luxor", "الأقصر"),
        new Governorate(25, "Qena", "قنا"),
        new Governorate(26, "North Sinai", "شمال سيناء"),
        new Governorate(27, "Sohag", "سوهاج"),
    };

    public static IReadOnlyList<Registration.Domain.Lookups.City> Cities { get; } = new[]
    {
        // Cairo
        new Registration.Domain.Lookups.City(1, 1, "15 May", "15 مايو"),
        new Registration.Domain.Lookups.City(2, 1, "Al Azbakeyah", "الازبكية"),
        new Registration.Domain.Lookups.City(3, 1, "Al Basatin", "البساتين"),
        new Registration.Domain.Lookups.City(4, 1, "Tebin", "التبين"),
        new Registration.Domain.Lookups.City(5, 1, "El-Khalifa", "الخليفة"),
        new Registration.Domain.Lookups.City(6, 1, "El darrasa", "الدراسة"),
        new Registration.Domain.Lookups.City(7, 1, "Aldarb Alahmar", "الدرب الاحمر"),
        new Registration.Domain.Lookups.City(8, 1, "Zawya al-Hamra", "الزاوية الحمراء"),
        new Registration.Domain.Lookups.City(9, 1, "El-Zaytoun", "الزيتون"),
        new Registration.Domain.Lookups.City(10, 1, "Sahel", "الساحل"),
        new Registration.Domain.Lookups.City(11, 1, "El Salam", "السلام"),
        new Registration.Domain.Lookups.City(12, 1, "Sayeda Zeinab", "السيدة زينب"),
        new Registration.Domain.Lookups.City(13, 1, "El Sharabeya", "الشرابية"),
        new Registration.Domain.Lookups.City(14, 1, "Shorouk", "مدينة الشروق"),
        new Registration.Domain.Lookups.City(15, 1, "El Daher", "الظاهر"),
        new Registration.Domain.Lookups.City(16, 1, "Ataba", "العتبة"),
        new Registration.Domain.Lookups.City(17, 1, "New Cairo", "القاهرة الجديدة"),
        new Registration.Domain.Lookups.City(18, 1, "El Marg", "المرج"),
        new Registration.Domain.Lookups.City(19, 1, "Ezbet el Nakhl", "عزبة النخل"),
        new Registration.Domain.Lookups.City(20, 1, "Matareya", "المطرية"),
        new Registration.Domain.Lookups.City(21, 1, "Maadi", "المعادى"),
        new Registration.Domain.Lookups.City(22, 1, "Maasara", "المعصرة"),
        new Registration.Domain.Lookups.City(23, 1, "Mokattam", "المقطم"),
        new Registration.Domain.Lookups.City(24, 1, "Manyal", "المنيل"),
        new Registration.Domain.Lookups.City(25, 1, "Mosky", "الموسكى"),
        new Registration.Domain.Lookups.City(26, 1, "Nozha", "النزهة"),
        new Registration.Domain.Lookups.City(27, 1, "Waily", "الوايلى"),
        new Registration.Domain.Lookups.City(28, 1, "Bab al-Shereia", "باب الشعرية"),
        new Registration.Domain.Lookups.City(29, 1, "Bolaq", "بولاق"),
        new Registration.Domain.Lookups.City(30, 1, "Garden City", "جاردن سيتى"),
        new Registration.Domain.Lookups.City(31, 1, "Hadayek El-Kobba", "حدائق القبة"),
        new Registration.Domain.Lookups.City(32, 1, "Helwan", "حلوان"),
        new Registration.Domain.Lookups.City(33, 1, "Dar Al Salam", "دار السلام"),
        new Registration.Domain.Lookups.City(34, 1, "Shubra", "شبرا"),
        new Registration.Domain.Lookups.City(35, 1, "Tura", "طره"),
        new Registration.Domain.Lookups.City(36, 1, "Abdeen", "عابدين"),
        new Registration.Domain.Lookups.City(37, 1, "Abaseya", "عباسية"),
        new Registration.Domain.Lookups.City(38, 1, "Ain Shams", "عين شمس"),
        new Registration.Domain.Lookups.City(39, 1, "Nasr City", "مدينة نصر"),
        new Registration.Domain.Lookups.City(40, 1, "New Heliopolis", "مصر الجديدة"),
        new Registration.Domain.Lookups.City(41, 1, "Masr Al Qadima", "مصر القديمة"),
        new Registration.Domain.Lookups.City(42, 1, "Mansheya Nasir", "منشية ناصر"),
        new Registration.Domain.Lookups.City(43, 1, "Badr City", "مدينة بدر"),
        new Registration.Domain.Lookups.City(44, 1, "Obour City", "مدينة العبور"),
        new Registration.Domain.Lookups.City(45, 1, "Cairo Downtown", "وسط البلد"),
        new Registration.Domain.Lookups.City(46, 1, "Zamalek", "الزمالك"),
        new Registration.Domain.Lookups.City(47, 1, "Kasr El Nile", "قصر النيل"),
        new Registration.Domain.Lookups.City(48, 1, "Rehab", "الرحاب"),
        new Registration.Domain.Lookups.City(49, 1, "Katameya", "القطامية"),
        new Registration.Domain.Lookups.City(50, 1, "Madinty", "مدينتي"),
        new Registration.Domain.Lookups.City(51, 1, "Rod Alfarag", "روض الفرج"),
        new Registration.Domain.Lookups.City(52, 1, "Sheraton", "شيراتون"),
        new Registration.Domain.Lookups.City(53, 1, "El-Gamaleya", "الجمالية"),
        new Registration.Domain.Lookups.City(54, 1, "10th of Ramadan City", "العاشر من رمضان"),
        new Registration.Domain.Lookups.City(55, 1, "Helmeyat Alzaytoun", "الحلمية"),
        new Registration.Domain.Lookups.City(56, 1, "New Nozha", "النزهة الجديدة"),
        new Registration.Domain.Lookups.City(57, 1, "Capital New", "العاصمة الإدارية"),
        // Giza
        new Registration.Domain.Lookups.City(58, 2, "Giza", "الجيزة"),
        new Registration.Domain.Lookups.City(59, 2, "Sixth of October", "السادس من أكتوبر"),
        new Registration.Domain.Lookups.City(60, 2, "Cheikh Zayed", "الشيخ زايد"),
        new Registration.Domain.Lookups.City(61, 2, "Hawamdiyah", "الحوامدية"),
        new Registration.Domain.Lookups.City(62, 2, "Al Badrasheen", "البدرشين"),
        new Registration.Domain.Lookups.City(63, 2, "Saf", "الصف"),
        new Registration.Domain.Lookups.City(64, 2, "Atfih", "أطفيح"),
        new Registration.Domain.Lookups.City(65, 2, "Al Ayat", "العياط"),
        new Registration.Domain.Lookups.City(66, 2, "Al-Bawaiti", "الباويطي"),
        new Registration.Domain.Lookups.City(67, 2, "ManshiyetAl Qanater", "منشأة القناطر"),
        new Registration.Domain.Lookups.City(68, 2, "Oaseem", "أوسيم"),
        new Registration.Domain.Lookups.City(69, 2, "Kerdasa", "كرداسة"),
        new Registration.Domain.Lookups.City(70, 2, "Abu Nomros", "أبو النمرس"),
        new Registration.Domain.Lookups.City(71, 2, "Kafr Ghati", "كفر غطاطي"),
        new Registration.Domain.Lookups.City(72, 2, "Manshiyet Al Bakari", "منشأة البكاري"),
        new Registration.Domain.Lookups.City(73, 2, "Dokki", "الدقى"),
        new Registration.Domain.Lookups.City(74, 2, "Agouza", "العجوزة"),
        new Registration.Domain.Lookups.City(75, 2, "Haram", "الهرم"),
        new Registration.Domain.Lookups.City(76, 2, "Warraq", "الوراق"),
        new Registration.Domain.Lookups.City(77, 2, "Imbaba", "امبابة"),
        new Registration.Domain.Lookups.City(78, 2, "Boulaq Dakrour", "بولاق الدكرور"),
        new Registration.Domain.Lookups.City(79, 2, "Al Wahat Al Baharia", "الواحات البحرية"),
        new Registration.Domain.Lookups.City(80, 2, "Omraneya", "العمرانية"),
        new Registration.Domain.Lookups.City(81, 2, "Moneeb", "المنيب"),
        new Registration.Domain.Lookups.City(82, 2, "Bin Alsarayat", "بين السرايات"),
        new Registration.Domain.Lookups.City(83, 2, "Kit Kat", "الكيت كات"),
        new Registration.Domain.Lookups.City(84, 2, "Mohandessin", "المهندسين"),
        new Registration.Domain.Lookups.City(85, 2, "Faisal", "فيصل"),
        new Registration.Domain.Lookups.City(86, 2, "Abu Rawash", "أبو رواش"),
        new Registration.Domain.Lookups.City(87, 2, "Hadayek Alahram", "حدائق الأهرام"),
        new Registration.Domain.Lookups.City(88, 2, "Haraneya", "الحرانية"),
        new Registration.Domain.Lookups.City(89, 2, "Hadayek October", "حدائق اكتوبر"),
        new Registration.Domain.Lookups.City(90, 2, "Saft Allaban", "صفط اللبن"),
        new Registration.Domain.Lookups.City(91, 2, "Smart Village", "القرية الذكية"),
        new Registration.Domain.Lookups.City(92, 2, "Ard Ellwaa", "ارض اللواء"),
        // Alexandria
        new Registration.Domain.Lookups.City(93, 3, "Abu Qir", "ابو قير"),
        new Registration.Domain.Lookups.City(94, 3, "Al Ibrahimeyah", "الابراهيمية"),
        new Registration.Domain.Lookups.City(95, 3, "Azarita", "الأزاريطة"),
        new Registration.Domain.Lookups.City(96, 3, "Anfoushi", "الانفوشى"),
        new Registration.Domain.Lookups.City(97, 3, "Dekheila", "الدخيلة"),
        new Registration.Domain.Lookups.City(98, 3, "El Soyof", "السيوف"),
        new Registration.Domain.Lookups.City(99, 3, "Ameria", "العامرية"),
        new Registration.Domain.Lookups.City(100, 3, "El Labban", "اللبان"),
        new Registration.Domain.Lookups.City(101, 3, "Al Mafrouza", "المفروزة"),
        new Registration.Domain.Lookups.City(102, 3, "El Montaza", "المنتزه"),
        new Registration.Domain.Lookups.City(103, 3, "Mansheya", "المنشية"),
        new Registration.Domain.Lookups.City(104, 3, "Naseria", "الناصرية"),
        new Registration.Domain.Lookups.City(105, 3, "Ambrozo", "امبروزو"),
        new Registration.Domain.Lookups.City(106, 3, "Bab Sharq", "باب شرق"),
        new Registration.Domain.Lookups.City(107, 3, "Bourj Alarab", "برج العرب"),
        new Registration.Domain.Lookups.City(108, 3, "Stanley", "ستانلى"),
        new Registration.Domain.Lookups.City(109, 3, "Smouha", "سموحة"),
        new Registration.Domain.Lookups.City(110, 3, "Sidi Bishr", "سيدى بشر"),
        new Registration.Domain.Lookups.City(111, 3, "Shads", "شدس"),
        new Registration.Domain.Lookups.City(112, 3, "Gheet Alenab", "غيط العنب"),
        new Registration.Domain.Lookups.City(113, 3, "Fleming", "فلمينج"),
        new Registration.Domain.Lookups.City(114, 3, "Victoria", "فيكتوريا"),
        new Registration.Domain.Lookups.City(115, 3, "Camp Shizar", "كامب شيزار"),
        new Registration.Domain.Lookups.City(116, 3, "Karmooz", "كرموز"),
        new Registration.Domain.Lookups.City(117, 3, "Mahta Alraml", "محطة الرمل"),
        new Registration.Domain.Lookups.City(118, 3, "Mina El-Basal", "مينا البصل"),
        new Registration.Domain.Lookups.City(119, 3, "Asafra", "العصافرة"),
        new Registration.Domain.Lookups.City(120, 3, "Agamy", "العجمي"),
        new Registration.Domain.Lookups.City(121, 3, "Bakos", "بكوس"),
        new Registration.Domain.Lookups.City(122, 3, "Boulkly", "بولكلي"),
        new Registration.Domain.Lookups.City(123, 3, "Cleopatra", "كليوباترا"),
        new Registration.Domain.Lookups.City(124, 3, "Glim", "جليم"),
        new Registration.Domain.Lookups.City(125, 3, "Al Mamurah", "المعمورة"),
        new Registration.Domain.Lookups.City(126, 3, "Al Mandara", "المندرة"),
        new Registration.Domain.Lookups.City(127, 3, "Moharam Bek", "محرم بك"),
        new Registration.Domain.Lookups.City(128, 3, "Elshatby", "الشاطبي"),
        new Registration.Domain.Lookups.City(129, 3, "Sidi Gaber", "سيدي جابر"),
        new Registration.Domain.Lookups.City(130, 3, "North Coast/sahel", "الساحل الشمالي"),
        new Registration.Domain.Lookups.City(131, 3, "Alhadra", "الحضرة"),
        new Registration.Domain.Lookups.City(132, 3, "Alattarin", "العطارين"),
        new Registration.Domain.Lookups.City(133, 3, "Sidi Kerir", "سيدي كرير"),
        new Registration.Domain.Lookups.City(134, 3, "Elgomrok", "الجمرك"),
        new Registration.Domain.Lookups.City(135, 3, "Al Max", "المكس"),
        new Registration.Domain.Lookups.City(136, 3, "Marina", "مارينا"),
        // Dakahlia
        new Registration.Domain.Lookups.City(137, 4, "Mansoura", "المنصورة"),
        new Registration.Domain.Lookups.City(138, 4, "Talkha", "طلخا"),
        new Registration.Domain.Lookups.City(139, 4, "Mitt Ghamr", "ميت غمر"),
        new Registration.Domain.Lookups.City(140, 4, "Dekernes", "دكرنس"),
        new Registration.Domain.Lookups.City(141, 4, "Aga", "أجا"),
        new Registration.Domain.Lookups.City(142, 4, "Menia El Nasr", "منية النصر"),
        new Registration.Domain.Lookups.City(143, 4, "Sinbillawin", "السنبلاوين"),
        new Registration.Domain.Lookups.City(144, 4, "El Kurdi", "الكردي"),
        new Registration.Domain.Lookups.City(145, 4, "Bani Ubaid", "بني عبيد"),
        new Registration.Domain.Lookups.City(146, 4, "Al Manzala", "المنزلة"),
        new Registration.Domain.Lookups.City(147, 4, "tami al'amdid", "تمي الأمديد"),
        new Registration.Domain.Lookups.City(148, 4, "aljamalia", "الجمالية"),
        new Registration.Domain.Lookups.City(149, 4, "Sherbin", "شربين"),
        new Registration.Domain.Lookups.City(150, 4, "Mataria", "المطرية"),
        new Registration.Domain.Lookups.City(151, 4, "Belqas", "بلقاس"),
        new Registration.Domain.Lookups.City(152, 4, "Meet Salsil", "ميت سلسيل"),
        new Registration.Domain.Lookups.City(153, 4, "Gamasa", "جمصة"),
        new Registration.Domain.Lookups.City(154, 4, "Mahalat Damana", "محلة دمنة"),
        new Registration.Domain.Lookups.City(155, 4, "Nabroh", "نبروه"),
        // Red Sea
        new Registration.Domain.Lookups.City(156, 5, "Hurghada", "الغردقة"),
        new Registration.Domain.Lookups.City(157, 5, "Ras Ghareb", "رأس غارب"),
        new Registration.Domain.Lookups.City(158, 5, "Safaga", "سفاجا"),
        new Registration.Domain.Lookups.City(159, 5, "El Qusiar", "القصير"),
        new Registration.Domain.Lookups.City(160, 5, "Marsa Alam", "مرسى علم"),
        new Registration.Domain.Lookups.City(161, 5, "Shalatin", "الشلاتين"),
        new Registration.Domain.Lookups.City(162, 5, "Halaib", "حلايب"),
        new Registration.Domain.Lookups.City(163, 5, "Aldahar", "الدهار"),
        // Beheira
        new Registration.Domain.Lookups.City(164, 6, "Damanhour", "دمنهور"),
        new Registration.Domain.Lookups.City(165, 6, "Kafr El Dawar", "كفر الدوار"),
        new Registration.Domain.Lookups.City(166, 6, "Rashid", "رشيد"),
        new Registration.Domain.Lookups.City(167, 6, "Edco", "إدكو"),
        new Registration.Domain.Lookups.City(168, 6, "Abu al-Matamir", "أبو المطامير"),
        new Registration.Domain.Lookups.City(169, 6, "Abu Homs", "أبو حمص"),
        new Registration.Domain.Lookups.City(170, 6, "Delengat", "الدلنجات"),
        new Registration.Domain.Lookups.City(171, 6, "Mahmoudiyah", "المحمودية"),
        new Registration.Domain.Lookups.City(172, 6, "Rahmaniyah", "الرحمانية"),
        new Registration.Domain.Lookups.City(173, 6, "Itai Baroud", "إيتاي البارود"),
        new Registration.Domain.Lookups.City(174, 6, "Housh Eissa", "حوش عيسى"),
        new Registration.Domain.Lookups.City(175, 6, "Shubrakhit", "شبراخيت"),
        new Registration.Domain.Lookups.City(176, 6, "Kom Hamada", "كوم حمادة"),
        new Registration.Domain.Lookups.City(177, 6, "Badr", "بدر"),
        new Registration.Domain.Lookups.City(178, 6, "Wadi Natrun", "وادي النطرون"),
        new Registration.Domain.Lookups.City(179, 6, "New Nubaria", "النوبارية الجديدة"),
        new Registration.Domain.Lookups.City(180, 6, "Alnoubareya", "النوبارية"),
        // Fayoum
        new Registration.Domain.Lookups.City(181, 7, "Fayoum", "الفيوم"),
        new Registration.Domain.Lookups.City(182, 7, "Fayoum El Gedida", "الفيوم الجديدة"),
        new Registration.Domain.Lookups.City(183, 7, "Tamiya", "طامية"),
        new Registration.Domain.Lookups.City(184, 7, "Snores", "سنورس"),
        new Registration.Domain.Lookups.City(185, 7, "Etsa", "إطسا"),
        new Registration.Domain.Lookups.City(186, 7, "Epschway", "إبشواي"),
        new Registration.Domain.Lookups.City(187, 7, "Yusuf El Sediaq", "يوسف الصديق"),
        new Registration.Domain.Lookups.City(188, 7, "Hadqa", "الحادقة"),
        new Registration.Domain.Lookups.City(189, 7, "Atsa", "اطسا"),
        new Registration.Domain.Lookups.City(190, 7, "Algamaa", "الجامعة"),
        new Registration.Domain.Lookups.City(191, 7, "Sayala", "السيالة"),
        // Gharbiya
        new Registration.Domain.Lookups.City(192, 8, "Tanta", "طنطا"),
        new Registration.Domain.Lookups.City(193, 8, "Al Mahalla Al Kobra", "المحلة الكبرى"),
        new Registration.Domain.Lookups.City(194, 8, "Kafr El Zayat", "كفر الزيات"),
        new Registration.Domain.Lookups.City(195, 8, "Zefta", "زفتى"),
        new Registration.Domain.Lookups.City(196, 8, "El Santa", "السنطة"),
        new Registration.Domain.Lookups.City(197, 8, "Qutour", "قطور"),
        new Registration.Domain.Lookups.City(198, 8, "Basion", "بسيون"),
        new Registration.Domain.Lookups.City(199, 8, "Samannoud", "سمنود"),
        // Ismailia
        new Registration.Domain.Lookups.City(200, 9, "Ismailia", "الإسماعيلية"),
        new Registration.Domain.Lookups.City(201, 9, "Fayed", "فايد"),
        new Registration.Domain.Lookups.City(202, 9, "Qantara Sharq", "القنطرة شرق"),
        new Registration.Domain.Lookups.City(203, 9, "Qantara Gharb", "القنطرة غرب"),
        new Registration.Domain.Lookups.City(204, 9, "El Tal El Kabier", "التل الكبير"),
        new Registration.Domain.Lookups.City(205, 9, "Abu Sawir", "أبو صوير"),
        new Registration.Domain.Lookups.City(206, 9, "Kasasien El Gedida", "القصاصين الجديدة"),
        new Registration.Domain.Lookups.City(207, 9, "Nefesha", "نفيشة"),
        new Registration.Domain.Lookups.City(208, 9, "Sheikh Zayed", "الشيخ زايد"),
        // Menofia
        new Registration.Domain.Lookups.City(209, 10, "Shbeen El Koom", "شبين الكوم"),
        new Registration.Domain.Lookups.City(210, 10, "Sadat City", "مدينة السادات"),
        new Registration.Domain.Lookups.City(211, 10, "Menouf", "منوف"),
        new Registration.Domain.Lookups.City(212, 10, "Sars El-Layan", "سرس الليان"),
        new Registration.Domain.Lookups.City(213, 10, "Ashmon", "أشمون"),
        new Registration.Domain.Lookups.City(214, 10, "Al Bagor", "الباجور"),
        new Registration.Domain.Lookups.City(215, 10, "Quesna", "قويسنا"),
        new Registration.Domain.Lookups.City(216, 10, "Berkat El Saba", "بركة السبع"),
        new Registration.Domain.Lookups.City(217, 10, "Tala", "تلا"),
        new Registration.Domain.Lookups.City(218, 10, "Al Shohada", "الشهداء"),
        // Minya
        new Registration.Domain.Lookups.City(219, 11, "Minya", "المنيا"),
        new Registration.Domain.Lookups.City(220, 11, "Minya El Gedida", "المنيا الجديدة"),
        new Registration.Domain.Lookups.City(221, 11, "El Adwa", "العدوة"),
        new Registration.Domain.Lookups.City(222, 11, "Magagha", "مغاغة"),
        new Registration.Domain.Lookups.City(223, 11, "Bani Mazar", "بني مزار"),
        new Registration.Domain.Lookups.City(224, 11, "Mattay", "مطاي"),
        new Registration.Domain.Lookups.City(225, 11, "Samalut", "سمالوط"),
        new Registration.Domain.Lookups.City(226, 11, "Madinat El Fekria", "المدينة الفكرية"),
        new Registration.Domain.Lookups.City(227, 11, "Meloy", "ملوي"),
        new Registration.Domain.Lookups.City(228, 11, "Deir Mawas", "دير مواس"),
        new Registration.Domain.Lookups.City(229, 11, "Abu Qurqas", "ابو قرقاص"),
        new Registration.Domain.Lookups.City(230, 11, "Ard Sultan", "ارض سلطان"),
        // Qaliubiya
        new Registration.Domain.Lookups.City(231, 12, "Banha", "بنها"),
        new Registration.Domain.Lookups.City(232, 12, "Qalyub", "قليوب"),
        new Registration.Domain.Lookups.City(233, 12, "Shubra Al Khaimah", "شبرا الخيمة"),
        new Registration.Domain.Lookups.City(234, 12, "Al Qanater Charity", "القناطر الخيرية"),
        new Registration.Domain.Lookups.City(235, 12, "Khanka", "الخانكة"),
        new Registration.Domain.Lookups.City(236, 12, "Kafr Shukr", "كفر شكر"),
        new Registration.Domain.Lookups.City(237, 12, "Tukh", "طوخ"),
        new Registration.Domain.Lookups.City(238, 12, "Qaha", "قها"),
        new Registration.Domain.Lookups.City(239, 12, "Obour", "العبور"),
        new Registration.Domain.Lookups.City(240, 12, "Khosous", "الخصوص"),
        new Registration.Domain.Lookups.City(241, 12, "Shibin Al Qanater", "شبين القناطر"),
        new Registration.Domain.Lookups.City(242, 12, "Mostorod", "مسطرد"),
        // New Valley
        new Registration.Domain.Lookups.City(243, 13, "El Kharga", "الخارجة"),
        new Registration.Domain.Lookups.City(244, 13, "Paris", "باريس"),
        new Registration.Domain.Lookups.City(245, 13, "Mout", "موط"),
        new Registration.Domain.Lookups.City(246, 13, "Farafra", "الفرافرة"),
        new Registration.Domain.Lookups.City(247, 13, "Balat", "بلاط"),
        new Registration.Domain.Lookups.City(248, 13, "Dakhla", "الداخلة"),
        // Suez
        new Registration.Domain.Lookups.City(249, 14, "Suez", "السويس"),
        new Registration.Domain.Lookups.City(250, 14, "Alganayen", "الجناين"),
        new Registration.Domain.Lookups.City(251, 14, "Ataqah", "عتاقة"),
        new Registration.Domain.Lookups.City(252, 14, "Ain Sokhna", "العين السخنة"),
        new Registration.Domain.Lookups.City(253, 14, "Faysal", "فيصل"),
        // Aswan
        new Registration.Domain.Lookups.City(254, 15, "Aswan", "أسوان"),
        new Registration.Domain.Lookups.City(255, 15, "Aswan El Gedida", "أسوان الجديدة"),
        new Registration.Domain.Lookups.City(256, 15, "Drau", "دراو"),
        new Registration.Domain.Lookups.City(257, 15, "Kom Ombo", "كوم أمبو"),
        new Registration.Domain.Lookups.City(258, 15, "Nasr Al Nuba", "نصر النوبة"),
        new Registration.Domain.Lookups.City(259, 15, "Kalabsha", "كلابشة"),
        new Registration.Domain.Lookups.City(260, 15, "Edfu", "إدفو"),
        new Registration.Domain.Lookups.City(261, 15, "Al-Radisiyah", "الرديسية"),
        new Registration.Domain.Lookups.City(262, 15, "Al Basilia", "البصيلية"),
        new Registration.Domain.Lookups.City(263, 15, "Al Sibaeia", "السباعية"),
        new Registration.Domain.Lookups.City(264, 15, "Abo Simbl Al Siyahia", "ابوسمبل السياحية"),
        new Registration.Domain.Lookups.City(265, 15, "Marsa Alam", "مرسى علم"),
        // Assiut
        new Registration.Domain.Lookups.City(266, 16, "Assiut", "أسيوط"),
        new Registration.Domain.Lookups.City(267, 16, "Assiut El Gedida", "أسيوط الجديدة"),
        new Registration.Domain.Lookups.City(268, 16, "Dayrout", "ديروط"),
        new Registration.Domain.Lookups.City(269, 16, "Manfalut", "منفلوط"),
        new Registration.Domain.Lookups.City(270, 16, "Qusiya", "القوصية"),
        new Registration.Domain.Lookups.City(271, 16, "Abnoub", "أبنوب"),
        new Registration.Domain.Lookups.City(272, 16, "Abu Tig", "أبو تيج"),
        new Registration.Domain.Lookups.City(273, 16, "El Ghanaim", "الغنايم"),
        new Registration.Domain.Lookups.City(274, 16, "Sahel Selim", "ساحل سليم"),
        new Registration.Domain.Lookups.City(275, 16, "El Badari", "البداري"),
        new Registration.Domain.Lookups.City(276, 16, "Sidfa", "صدفا"),
        // Beni Suef
        new Registration.Domain.Lookups.City(277, 17, "Bani Sweif", "بني سويف"),
        new Registration.Domain.Lookups.City(278, 17, "Beni Suef El Gedida", "بني سويف الجديدة"),
        new Registration.Domain.Lookups.City(279, 17, "Al Wasta", "الواسطى"),
        new Registration.Domain.Lookups.City(280, 17, "Naser", "ناصر"),
        new Registration.Domain.Lookups.City(281, 17, "Ehnasia", "إهناسيا"),
        new Registration.Domain.Lookups.City(282, 17, "beba", "ببا"),
        new Registration.Domain.Lookups.City(283, 17, "Fashn", "الفشن"),
        new Registration.Domain.Lookups.City(284, 17, "Somasta", "سمسطا"),
        new Registration.Domain.Lookups.City(285, 17, "Alabbaseri", "الاباصيرى"),
        new Registration.Domain.Lookups.City(286, 17, "Mokbel", "مقبل"),
        // Port Said
        new Registration.Domain.Lookups.City(287, 18, "PorSaid", "بورسعيد"),
        new Registration.Domain.Lookups.City(288, 18, "Port Fouad", "بورفؤاد"),
        new Registration.Domain.Lookups.City(289, 18, "Alarab", "العرب"),
        new Registration.Domain.Lookups.City(290, 18, "Zohour", "حى الزهور"),
        new Registration.Domain.Lookups.City(291, 18, "Alsharq", "حى الشرق"),
        new Registration.Domain.Lookups.City(292, 18, "Aldawahi", "حى الضواحى"),
        new Registration.Domain.Lookups.City(293, 18, "Almanakh", "حى المناخ"),
        new Registration.Domain.Lookups.City(294, 18, "Mubarak", "حى مبارك"),
        // Damietta
        new Registration.Domain.Lookups.City(295, 19, "Damietta", "دمياط"),
        new Registration.Domain.Lookups.City(296, 19, "New Damietta", "دمياط الجديدة"),
        new Registration.Domain.Lookups.City(297, 19, "Ras El Bar", "رأس البر"),
        new Registration.Domain.Lookups.City(298, 19, "Faraskour", "فارسكور"),
        new Registration.Domain.Lookups.City(299, 19, "Zarqa", "الزرقا"),
        new Registration.Domain.Lookups.City(300, 19, "alsaru", "السرو"),
        new Registration.Domain.Lookups.City(301, 19, "alruwda", "الروضة"),
        new Registration.Domain.Lookups.City(302, 19, "Kafr El-Batikh", "كفر البطيخ"),
        new Registration.Domain.Lookups.City(303, 19, "Azbet Al Burg", "عزبة البرج"),
        new Registration.Domain.Lookups.City(304, 19, "Meet Abou Ghalib", "ميت أبو غالب"),
        new Registration.Domain.Lookups.City(305, 19, "Kafr Saad", "كفر سعد"),
        // Sharkia
        new Registration.Domain.Lookups.City(306, 20, "Zagazig", "الزقازيق"),
        new Registration.Domain.Lookups.City(307, 20, "Al Ashr Men Ramadan", "العاشر من رمضان"),
        new Registration.Domain.Lookups.City(308, 20, "Minya Al Qamh", "منيا القمح"),
        new Registration.Domain.Lookups.City(309, 20, "Belbeis", "بلبيس"),
        new Registration.Domain.Lookups.City(310, 20, "Mashtoul El Souq", "مشتول السوق"),
        new Registration.Domain.Lookups.City(311, 20, "Qenaiat", "القنايات"),
        new Registration.Domain.Lookups.City(312, 20, "Abu Hammad", "أبو حماد"),
        new Registration.Domain.Lookups.City(313, 20, "El Qurain", "القرين"),
        new Registration.Domain.Lookups.City(314, 20, "Hehia", "ههيا"),
        new Registration.Domain.Lookups.City(315, 20, "Abu Kabir", "أبو كبير"),
        new Registration.Domain.Lookups.City(316, 20, "Faccus", "فاقوس"),
        new Registration.Domain.Lookups.City(317, 20, "El Salihia El Gedida", "الصالحية الجديدة"),
        new Registration.Domain.Lookups.City(318, 20, "Al Ibrahimiyah", "الإبراهيمية"),
        new Registration.Domain.Lookups.City(319, 20, "Deirb Negm", "ديرب نجم"),
        new Registration.Domain.Lookups.City(320, 20, "Kafr Saqr", "كفر صقر"),
        new Registration.Domain.Lookups.City(321, 20, "Awlad Saqr", "أولاد صقر"),
        new Registration.Domain.Lookups.City(322, 20, "Husseiniya", "الحسينية"),
        new Registration.Domain.Lookups.City(323, 20, "san alhajar alqablia", "صان الحجر القبلية"),
        new Registration.Domain.Lookups.City(324, 20, "Manshayat Abu Omar", "منشأة أبو عمر"),
        // South Sinai
        new Registration.Domain.Lookups.City(325, 21, "Al Toor", "الطور"),
        new Registration.Domain.Lookups.City(326, 21, "Sharm El-Shaikh", "شرم الشيخ"),
        new Registration.Domain.Lookups.City(327, 21, "Dahab", "دهب"),
        new Registration.Domain.Lookups.City(328, 21, "Nuweiba", "نويبع"),
        new Registration.Domain.Lookups.City(329, 21, "Taba", "طابا"),
        new Registration.Domain.Lookups.City(330, 21, "Saint Catherine", "سانت كاترين"),
        new Registration.Domain.Lookups.City(331, 21, "Abu Redis", "أبو رديس"),
        new Registration.Domain.Lookups.City(332, 21, "Abu Zenaima", "أبو زنيمة"),
        new Registration.Domain.Lookups.City(333, 21, "Ras Sidr", "رأس سدر"),
        // Kafr Al sheikh
        new Registration.Domain.Lookups.City(334, 22, "Kafr El Sheikh", "كفر الشيخ"),
        new Registration.Domain.Lookups.City(335, 22, "Kafr El Sheikh Downtown", "وسط البلد كفر الشيخ"),
        new Registration.Domain.Lookups.City(336, 22, "Desouq", "دسوق"),
        new Registration.Domain.Lookups.City(337, 22, "Fooh", "فوه"),
        new Registration.Domain.Lookups.City(338, 22, "Metobas", "مطوبس"),
        new Registration.Domain.Lookups.City(339, 22, "Burg Al Burullus", "برج البرلس"),
        new Registration.Domain.Lookups.City(340, 22, "Baltim", "بلطيم"),
        new Registration.Domain.Lookups.City(341, 22, "Masief Baltim", "مصيف بلطيم"),
        new Registration.Domain.Lookups.City(342, 22, "Hamol", "الحامول"),
        new Registration.Domain.Lookups.City(343, 22, "Bella", "بيلا"),
        new Registration.Domain.Lookups.City(344, 22, "Riyadh", "الرياض"),
        new Registration.Domain.Lookups.City(345, 22, "Sidi Salm", "سيدي سالم"),
        new Registration.Domain.Lookups.City(346, 22, "Qellen", "قلين"),
        new Registration.Domain.Lookups.City(347, 22, "Sidi Ghazi", "سيدي غازي"),
        // Matrouh
        new Registration.Domain.Lookups.City(348, 23, "Marsa Matrouh", "مرسى مطروح"),
        new Registration.Domain.Lookups.City(349, 23, "El Hamam", "الحمام"),
        new Registration.Domain.Lookups.City(350, 23, "Alamein", "العلمين"),
        new Registration.Domain.Lookups.City(351, 23, "Dabaa", "الضبعة"),
        new Registration.Domain.Lookups.City(352, 23, "Al-Nagila", "النجيلة"),
        new Registration.Domain.Lookups.City(353, 23, "Sidi Brani", "سيدي براني"),
        new Registration.Domain.Lookups.City(354, 23, "Salloum", "السلوم"),
        new Registration.Domain.Lookups.City(355, 23, "Siwa", "سيوة"),
        new Registration.Domain.Lookups.City(356, 23, "Marina", "مارينا"),
        new Registration.Domain.Lookups.City(357, 23, "North Coast", "الساحل الشمالى"),
        // Luxor
        new Registration.Domain.Lookups.City(358, 24, "Luxor", "الأقصر"),
        new Registration.Domain.Lookups.City(359, 24, "New Luxor", "الأقصر الجديدة"),
        new Registration.Domain.Lookups.City(360, 24, "Esna", "إسنا"),
        new Registration.Domain.Lookups.City(361, 24, "New Tiba", "طيبة الجديدة"),
        new Registration.Domain.Lookups.City(362, 24, "Al ziynia", "الزينية"),
        new Registration.Domain.Lookups.City(363, 24, "Al Bayadieh", "البياضية"),
        new Registration.Domain.Lookups.City(364, 24, "Al Qarna", "القرنة"),
        new Registration.Domain.Lookups.City(365, 24, "Armant", "أرمنت"),
        new Registration.Domain.Lookups.City(366, 24, "Al Tud", "الطود"),
        // Qena
        new Registration.Domain.Lookups.City(367, 25, "Qena", "قنا"),
        new Registration.Domain.Lookups.City(368, 25, "New Qena", "قنا الجديدة"),
        new Registration.Domain.Lookups.City(369, 25, "Abu Tesht", "ابو طشت"),
        new Registration.Domain.Lookups.City(370, 25, "Nag Hammadi", "نجع حمادي"),
        new Registration.Domain.Lookups.City(371, 25, "Deshna", "دشنا"),
        new Registration.Domain.Lookups.City(372, 25, "Alwaqf", "الوقف"),
        new Registration.Domain.Lookups.City(373, 25, "Qaft", "قفط"),
        new Registration.Domain.Lookups.City(374, 25, "Naqada", "نقادة"),
        new Registration.Domain.Lookups.City(375, 25, "Farshout", "فرشوط"),
        new Registration.Domain.Lookups.City(376, 25, "Quos", "قوص"),
        // North Sinai
        new Registration.Domain.Lookups.City(377, 26, "Arish", "العريش"),
        new Registration.Domain.Lookups.City(378, 26, "Sheikh Zowaid", "الشيخ زويد"),
        new Registration.Domain.Lookups.City(379, 26, "Nakhl", "نخل"),
        new Registration.Domain.Lookups.City(380, 26, "Rafah", "رفح"),
        new Registration.Domain.Lookups.City(381, 26, "Bir al-Abed", "بئر العبد"),
        new Registration.Domain.Lookups.City(382, 26, "Al Hasana", "الحسنة"),
        // Sohag
        new Registration.Domain.Lookups.City(383, 27, "Sohag", "سوهاج"),
        new Registration.Domain.Lookups.City(384, 27, "Sohag El Gedida", "سوهاج الجديدة"),
        new Registration.Domain.Lookups.City(385, 27, "Akhmeem", "أخميم"),
        new Registration.Domain.Lookups.City(386, 27, "Akhmim El Gedida", "أخميم الجديدة"),
        new Registration.Domain.Lookups.City(387, 27, "Albalina", "البلينا"),
        new Registration.Domain.Lookups.City(388, 27, "El Maragha", "المراغة"),
        new Registration.Domain.Lookups.City(389, 27, "almunsha'a", "المنشأة"),
        new Registration.Domain.Lookups.City(390, 27, "Dar AISalaam", "دار السلام"),
        new Registration.Domain.Lookups.City(391, 27, "Gerga", "جرجا"),
        new Registration.Domain.Lookups.City(392, 27, "Jahina Al Gharbia", "جهينة الغربية"),
        new Registration.Domain.Lookups.City(393, 27, "Saqilatuh", "ساقلته"),
        new Registration.Domain.Lookups.City(394, 27, "Tama", "طما"),
        new Registration.Domain.Lookups.City(395, 27, "Tahta", "طهطا"),
        new Registration.Domain.Lookups.City(396, 27, "Alkawthar", "الكوثر"),
    };
}
