namespace Registration.Domain.Lookups;

/// <summary>
/// A governorate lookup. Names are kept in both English and Arabic to support a
/// bilingual UI. Identifiers are fixed seed values, so the id is assigned
/// explicitly rather than generated by the database.
/// </summary>
public sealed class Governorate
{
    private readonly List<City> _cities = new();

    public Governorate(int id, string nameEn, string nameAr, bool isActive = true)
    {
        Id = id;
        NameEn = nameEn;
        NameAr = nameAr;
        IsActive = isActive;
    }

    private Governorate()
    {
    }

    public int Id { get; private set; }

    public string NameEn { get; private set; } = null!;

    public string NameAr { get; private set; } = null!;

    public bool IsActive { get; private set; }

    public IReadOnlyCollection<City> Cities => _cities.AsReadOnly();
}
